default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # ADDED: Increase the time a thread will wait to get a connection from the pool (default is 5 seconds)
  checkout_timeout: 10 # seconds (or higher, e.g., 20)
  timeout: 5000
  # ADDED: Supabase requires SSL for external connections
  sslmode: require
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
